--------------------------------------------------------
--Project Located in https://github.com/Preranakh/SWARM
--  File created - Saturday-April-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASP_NET_ROLES
--------------------------------------------------------

  CREATE TABLE "ASP_NET_ROLES" 
   (	"ID" NVARCHAR2(450), 
	"NAME" NVARCHAR2(256), 
	"NORMALIZED_NAME" NVARCHAR2(256), 
	"CONCURRENCY_STAMP" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_ROLE_CLAIMS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_ROLE_CLAIMS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLE_ID" NVARCHAR2(450), 
	"CLAIM_TYPE" NVARCHAR2(2000), 
	"CLAIM_VALUE" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USERS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USERS" 
   (	"ID" NVARCHAR2(450), 
	"FIRST_NAME" NVARCHAR2(25), 
	"LASTNAME" NVARCHAR2(25), 
	"USER_NAME" NVARCHAR2(256), 
	"NORMALIZED_USER_NAME" NVARCHAR2(256), 
	"EMAIL" NVARCHAR2(256), 
	"NORMALIZED_EMAIL" NVARCHAR2(256), 
	"EMAIL_CONFIRMED" NUMBER(1,0), 
	"PASSWORD_HASH" NVARCHAR2(2000), 
	"SECURITY_STAMP" NVARCHAR2(2000), 
	"CONCURRENCY_STAMP" NVARCHAR2(2000), 
	"PHONE_NUMBER" NVARCHAR2(2000), 
	"PHONE_NUMBER_CONFIRMED" NUMBER(1,0), 
	"TWO_FACTOR_ENABLED" NUMBER(1,0), 
	"LOCKOUT_END" TIMESTAMP (7) WITH TIME ZONE, 
	"LOCKOUT_ENABLED" NUMBER(1,0), 
	"ACCESS_FAILED_COUNT" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_CLAIMS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_CLAIMS" 
   (	"ID" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NVARCHAR2(450), 
	"CLAIM_TYPE" NVARCHAR2(2000), 
	"CLAIM_VALUE" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_LOGINS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_LOGINS" 
   (	"LOGIN_PROVIDER" NVARCHAR2(128), 
	"PROVIDER_KEY" NVARCHAR2(128), 
	"PROVIDER_DISPLAY_NAME" NVARCHAR2(2000), 
	"USER_ID" NVARCHAR2(450)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_ROLES" 
   (	"USER_ID" NVARCHAR2(450), 
	"ROLE_ID" NVARCHAR2(450)
   ) ;
--------------------------------------------------------
--  DDL for Table ASP_NET_USER_TOKENS
--------------------------------------------------------

  CREATE TABLE "ASP_NET_USER_TOKENS" 
   (	"USER_ID" NVARCHAR2(450), 
	"LOGIN_PROVIDER" NVARCHAR2(128), 
	"NAME" NVARCHAR2(128), 
	"VALUE" NVARCHAR2(2000)
   ) ;
--------------------------------------------------------
--  DDL for Table DEVICE_CODES
--------------------------------------------------------

  CREATE TABLE "DEVICE_CODES" 
   (	"USER_CODE" NVARCHAR2(200), 
	"DEVICE_CODE" NVARCHAR2(200), 
	"SUBJECT_ID" NVARCHAR2(200), 
	"SESSION_ID" NVARCHAR2(100), 
	"CLIENT_ID" NVARCHAR2(200), 
	"DESCRIPTION" NVARCHAR2(200), 
	"CREATION_TIME" TIMESTAMP (7), 
	"EXPIRATION" TIMESTAMP (7), 
	"DATA" NCLOB
   ) ;
--------------------------------------------------------
--  DDL for Table PERSISTED_GRANTS
--------------------------------------------------------

  CREATE TABLE "PERSISTED_GRANTS" 
   (	"KEY" NVARCHAR2(200), 
	"TYPE" NVARCHAR2(50), 
	"SUBJECT_ID" NVARCHAR2(200), 
	"SESSION_ID" NVARCHAR2(100), 
	"CLIENT_ID" NVARCHAR2(200), 
	"DESCRIPTION" NVARCHAR2(200), 
	"CREATION_TIME" TIMESTAMP (7), 
	"EXPIRATION" TIMESTAMP (7), 
	"CONSUMED_TIME" TIMESTAMP (7), 
	"DATA" NCLOB
   ) ;
--------------------------------------------------------
--  DDL for Table __EFMigrationsHistory
--------------------------------------------------------

  CREATE TABLE "__EFMigrationsHistory" 
   (	"MigrationId" NVARCHAR2(150), 
	"ProductVersion" NVARCHAR2(32)
   ) ;
REM INSERTING into ASP_NET_ROLES
SET DEFINE OFF;
REM INSERTING into ASP_NET_ROLE_CLAIMS
SET DEFINE OFF;
REM INSERTING into ASP_NET_USERS
SET DEFINE OFF;
Insert into ASP_NET_USERS (ID,FIRST_NAME,LASTNAME,USER_NAME,NORMALIZED_USER_NAME,EMAIL,NORMALIZED_EMAIL,EMAIL_CONFIRMED,PASSWORD_HASH,SECURITY_STAMP,CONCURRENCY_STAMP,PHONE_NUMBER,PHONE_NUMBER_CONFIRMED,TWO_FACTOR_ENABLED,LOCKOUT_END,LOCKOUT_ENABLED,ACCESS_FAILED_COUNT) values ('6201427d-f9bf-4643-a7d1-8fe457108608',null,null,'preranak@udel.edu','PRERANAK@UDEL.EDU','preranak@udel.edu','PRERANAK@UDEL.EDU',1,'AQAAAAEAACcQAAAAELPC32G/NIGblMpsGCjFqPehX6+aetxQ+2UMbsrTRnbZC16CRnGoZA6EKIz3ldCmnA==','DCERZ7LINKFQOUEV6LSKTUI2GQ7HUMQ3','bf695d9e-a7fc-4e89-b246-529f51e5f6e7',null,0,0,null,1,0);
REM INSERTING into ASP_NET_USER_CLAIMS
SET DEFINE OFF;
REM INSERTING into ASP_NET_USER_LOGINS
SET DEFINE OFF;
REM INSERTING into ASP_NET_USER_ROLES
SET DEFINE OFF;
REM INSERTING into ASP_NET_USER_TOKENS
SET DEFINE OFF;
REM INSERTING into DEVICE_CODES
SET DEFINE OFF;
REM INSERTING into PERSISTED_GRANTS
SET DEFINE OFF;
REM INSERTING into "__EFMigrationsHistory"
SET DEFINE OFF;
Insert into "__EFMigrationsHistory" ("MigrationId","ProductVersion") values ('20220331234453_init','5.0.15');
Insert into "__EFMigrationsHistory" ("MigrationId","ProductVersion") values ('20220331235252_v1','5.0.15');
--------------------------------------------------------
--  Constraints for Table ASP_NET_ROLES
--------------------------------------------------------

  ALTER TABLE "ASP_NET_ROLES" ADD CONSTRAINT "PK_ASP_NET_ROLES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_ROLES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_ROLE_CLAIMS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_ROLE_CLAIMS" ADD CONSTRAINT "PK_ASP_NET_ROLE_CLAIMS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_ROLE_CLAIMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_ROLE_CLAIMS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USERS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USERS" ADD CONSTRAINT "PK_ASP_NET_USERS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("EMAIL_CONFIRMED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("PHONE_NUMBER_CONFIRMED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("TWO_FACTOR_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("LOCKOUT_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USERS" MODIFY ("ACCESS_FAILED_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_CLAIMS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_CLAIMS" ADD CONSTRAINT "PK_ASP_NET_USER_CLAIMS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USER_CLAIMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_CLAIMS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_LOGINS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_LOGINS" ADD CONSTRAINT "PK_ASP_NET_USER_LOGINS" PRIMARY KEY ("LOGIN_PROVIDER", "PROVIDER_KEY")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USER_LOGINS" MODIFY ("LOGIN_PROVIDER" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_LOGINS" MODIFY ("PROVIDER_KEY" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_LOGINS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_ROLES" ADD CONSTRAINT "PK_ASP_NET_USER_ROLES" PRIMARY KEY ("USER_ID", "ROLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USER_ROLES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASP_NET_USER_TOKENS
--------------------------------------------------------

  ALTER TABLE "ASP_NET_USER_TOKENS" ADD CONSTRAINT "PK_ASP_NET_USER_TOKENS" PRIMARY KEY ("USER_ID", "LOGIN_PROVIDER", "NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ASP_NET_USER_TOKENS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_TOKENS" MODIFY ("LOGIN_PROVIDER" NOT NULL ENABLE);
  ALTER TABLE "ASP_NET_USER_TOKENS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVICE_CODES
--------------------------------------------------------

  ALTER TABLE "DEVICE_CODES" ADD CONSTRAINT "PK_DEVICE_CODES" PRIMARY KEY ("USER_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "DEVICE_CODES" MODIFY ("USER_CODE" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("DEVICE_CODE" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("EXPIRATION" NOT NULL ENABLE);
  ALTER TABLE "DEVICE_CODES" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSISTED_GRANTS
--------------------------------------------------------

  ALTER TABLE "PERSISTED_GRANTS" ADD CONSTRAINT "PK_PERSISTED_GRANTS" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE;
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "PERSISTED_GRANTS" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table __EFMigrationsHistory
--------------------------------------------------------

  ALTER TABLE "__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
  USING INDEX  ENABLE;
  ALTER TABLE "__EFMigrationsHistory" MODIFY ("MigrationId" NOT NULL ENABLE);
  ALTER TABLE "__EFMigrationsHistory" MODIFY ("ProductVersion" NOT NULL ENABLE);
